baseURL = "https://adamnnagy.github.io/portfolio-2025-hugo/"
languageCode = 'en-us'
title = 'Ádám Nagy'
theme = ""
publishDir = "docs"

[markup.goldmark.renderer]
  unsafe = true

[params]
heroBackground = "images/hero-bg.jpg"
heroSubtitle = "Creative work across film, code and design"
heroVideo = "videos/hero.mp4"